### ISSUE TITLE
Guard against conflicting plugins

### ISSUE THREAD

**Issue by Zrrg** [thpatch/thcrap#59] opened 2016-10-05 16:04 UTC
It worked fine before I've tried to install jisakujien's hitbox patch (http://www.mediafire.com/download.php?vive3tpn34n45qe). I've replaced d3d8.dll and put hitbox.png into game folder. it works fine while I launch game via vpatch and crashes, if I launch thcrap with vpatch.exe as game exe. Game gives memory error at start and crashes, when Shift is pressed.

**Comment by Zrrg** [comment] 2016-10-24 05:26
Strangely, it worked fine on other computer on Win7, so it may be single case. This is WinXP. It says "The instruction at A referenced memory at B . The memory could not be read"
![59ws4aauwug](https://cloud.githubusercontent.com/assets/11311379/19634381/1acb807c-99c3-11e6-9cf6-354454c3cd51.jpg)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/546992/thcrap_log.txt)

**Comment by nmlgc** [comment] 2016-10-25 20:20
I can't even get that box by provoking a memory read access violation on a clean Windows XP installation, so it's very likely that something else on your system injects its code into the process. Let's find out: Please replace the thcrap.dll and thcrap_tsa.dll with the versions in the attached .zip file, then crash the game again and post both the message box (the addresses might be different) and thcrap_log.txt.
[thcrap Module logging.zip](https://github.com/thpatch/thcrap/files/551699/thcrap.Module.logging.zip)

**Comment by Zrrg** [comment] 2016-10-26 16:15
![pic](https://cloud.githubusercontent.com/assets/11311379/19734470/57a5245a-9bb0-11e6-86c4-8e798f18d82f.jpg)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/553825/thcrap_log.txt)

**Comment by nmlgc** [comment] 2016-10-26 18:22
Could you repeat this with the Sandbox patch in your configuration? (Since the crash happens during the first stage, I put the necessary debugging code into the .msg patcher, and it's guaranteed that vpatch is initialized by then. And without the Sandbox patch, no .msg files are getting patched.)

**Comment by Zrrg** [comment] 2016-10-26 19:41
![image](https://cloud.githubusercontent.com/assets/11311379/19742305/1fa77d92-9bcd-11e6-9467-744617b820fe.png)
[thcrap_log.txt](https://github.com/thpatch/thcrap/files/554288/thcrap_log.txt)

**Comment by nmlgc** [comment] 2016-11-14 00:00
Turns out the problem was the fact that @Zrrg had a *second* instance of thcrap_tsa.dll, thcrap_tsa.dll**1**, which got loaded into the process. This happened because [we're calling `FindFirstFile()` with `"*.dll"` to enumerate DLLs](https://github.com/thpatch/thcrap/blob/master/thcrap/src/plugin.c#L52), which also retrieves *any* file whose extension merely *starts* with `.dll` because the 8.3 name of a file with a longer extension simply includes the first three characters, and [Windows still has to support 8.3 name parameters for `FindFirstFile()` for reasons of backwards compatibility](https://blogs.msdn.microsoft.com/oldnewthing/20050720-16/?p=34883).

I've wanted to do something about this for a while, especially since the Visual Studio solution currently puts both the Debug (*_d.dll) and Release versions of all binaries into the same output directory. The best solution I can think of right now would be to look at the global reflected list of functions, check if a newly loaded DLL would overwrite any of them, and then either silently ignore the wrong DLL if we can identify it for sure (which we can by searching the list of imported DLLs for the Visual C++ runtimes), or show a conflict warning message.

Which probably should be nicely formatted, meaning that this needs a GUI to be fully done.

**Comment by brliron** [comment] 2020-01-05 19:24
Duplicate of #116

**Closed by brliron** 2020-01-05 19:24 UTC
Labels: bug
