### ISSUE TITLE
th10 - cannot review replays of lunatic level continuously after patched by Simplified Chinese translation

### ISSUE THREAD

**Issue by 365daysdreamer** [thpatch/thcrap#157] opened 2021-11-08 08:30 UTC
I tested replays of Normal level and Lunatic level with or without VsyncPatch and the Simplified Chinese translation patch. It illustrated that VsyncPatch didn't affect the use, but the Simplified Chinese translation patch works well for the former one and has a bug on the latter one. **When reviewing a replay from a stage, MoF will stop at the end of this stage and not continue to the next one.**

**Comment by 32th-System** [comment] 2021-11-08 10:02
Duplicate of https://github.com/thpatch/thcrap-tsa/issues/46 (not to be rude, it's just that we already have a bug report for this exact problem)

**Closed by 32th-System** 2021-11-08 10:02 UTC
