### ISSUE TITLE
Use modern wizard-like setup UI instead of long complex list.

### ISSUE THREAD

**Issue by Yanstory** [thpatch/thcrap#101] opened 2019-05-27 12:46 UTC
Like usual windows, one example is troubleshooting. It's more friendly than currently using.
![image](https://user-images.githubusercontent.com/5153875/58420310-84679300-80bf-11e9-9770-88d76a199b9b.png)
And can add some more operations like:

- asking for custom patch server URL besides of using command
- existed patch js simple editing
- ``game.js`` simple editing
- patched shortcut generator

and more.

**Comment by brliron** [comment] 2019-05-27 13:17
Yeah, I also thought about making thcrap_configure a wizard. I even made a mockup: [link].
On the other hand, spending a lot of times reading blog articles from Microsoft employees, from the co-founder of StackOverflow, from a Mozilla designer, and from other sources led me to think that too many choices are bad. When a user doesn't need a feature, he still have to understand that feature, and to decide that he doesn't need it.
And you will see that in my mockup - it actually has *less* features than the current thcrap_configure. And the kind of features you suggest definitely don't fit in a "keep it simple" design.
On the other hand, I'm not against an expert mode. People bad with computer tend to know they're bad, and they wouldn't dare clicking on a "Expert mode" link.

De: notifications@github.com
Envoyé: 27 mai 2019 14:46
À: thcrap@noreply.github.com
Répondre à: reply@reply.github.com
Cc: subscribed@noreply.github.com
Objet: [thpatch/thcrap] Use modern wizard-like setup UI instead of long complex list. (#101)


Like usual windows, one example is troubleshooting. It's more friendly than currently using.
[image]<https://user-images.githubusercontent.com/5153875/58420310-84679300-80bf-11e9-9770-88d76a199b9b.png>
And can add some more operations like:

  *   asking for custom patch server URL besides of using command
  *   existed patch js simple editing
  *   game.js simple editing
  *   patched shortcut generator

and more.

**Comment by DankRank** [comment] 2019-05-27 15:02
It's gonna happen sooner or later.
![image](https://user-images.githubusercontent.com/4050457/58427667-f97b9e00-80a8-11e9-8161-c4eba7799081.png)

**Comment by Tudi20** [comment] 2020-11-08 00:26
Isn't this technically a duplicate of #8 ?

**Comment by brliron** [comment] 2022-02-21 13:05
It have been done for a while

**Closed by brliron** 2022-02-21 13:05 UTC
