### ISSUE TITLE
[MoF] Replay flow breaks with patch enabled

### ISSUE THREAD

**Issue by N30N014** [thpatch/thcrap#160] opened 2021-11-16 20:39 UTC
By running the game with thcrap enabled (tested using only the EN language pack), starting a replay of a stage makes it end at that stage instead of automatically continuing into the next ones. Tried without thcrap, vpatch enabled and the issue does not present itself.
Non-steam version, latest thcrap release (2021-10-24) and 2020-04-27 tested as well, no changes.

**Comment by 32th-System** [comment] 2021-11-16 20:53
Duplicate of https://github.com/thpatch/thcrap-tsa/issues/46 (not to be rude, someone simply reported the issue before you)

**Closed by 32th-System** 2021-11-16 20:53 UTC
